version: '3.8'

services:
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
      args:
        VITE_OPENCAGE_TOKEN: ${VITE_OPENCAGE_TOKEN}
    volumes:
      - ./src/frontend:/app
      - /app/node_modules  # avoid overwriting node_modules
    working_dir: /app
    command: ["npm", "run", "preview", "--", "--port", "5173", "--host"]
    ports:
      - "5173:5173"
    environment:
      - API_HOST=host.docker.internal

  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./src/proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Linux compatibility

  # model: # Please add your docker compose configuration for the model

volumes:
  frontend-dist:
