version: '3.8'

services:
  frontend:
    build:
      context: ./src/frontend
      target: build
    volumes:
      - frontend-dist:/app/dist

  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./src/proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend-dist:/usr/share/nginx/html
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Linux compatibility

  # model: # Please add your docker compose configuration for the model

volumes:
  frontend-dist:
