version: '3.8'

services:
  frontend:
    build:
      context: ./src/frontend
      target: build
    volumes:
      - frontend-dist:/app/dist

  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./src/proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend-dist:/usr/share/nginx/html
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Linux compatibility
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web Console
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set local http://minio:9000 admin admin123 &&
      mc mb -p local/cc-fraud-detection-2025 ||
      echo 'Bucket already exists'
      "
  # model: # Please add your docker compose configuration for the model

volumes:
  frontend-dist:
  minio-data: