services:
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
      args:
        VITE_OPENCAGE_TOKEN: ${VITE_OPENCAGE_TOKEN}
    working_dir: /app
    command: ["npm", "run", "preview", "--", "--port", "5173", "--host"]
    ports:
      - "5173:5173"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5173"]
      interval: 5s
      timeout: 2s
      retries: 10
    environment:
      - API_HOST=host.docker.internal
    networks:
      - ml-network

  nginx:
    image: nginx:alpine
    depends_on:
      - api
      - frontend
    ports:
      - "3000:80"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - ./src/proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Linux compatibility
    networks:
      - ml-network

  mlflow:
    image: python:3.9-slim
    container_name: mlflow-server
    ports:
      - "5000:5000"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "python3 -c \"import http.client; conn = http.client.HTTPConnection('localhost', 5000); conn.request('GET', '/'); resp = conn.getresponse(); exit(0) if resp.status == 200 else exit(1)\""
        ]
      interval: 5s
      timeout: 2s
      retries: 5
    environment:
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      MLFLOW_TRACKING_USERNAME: ${MLFLOW_TRACKING_USERNAME}
      MLFLOW_TRACKING_PASSWORD: ${MLFLOW_TRACKING_PASSWORD}
    command: >
      bash -c "pip install mlflow psycopg2-binary boto3 && mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db"
    networks:
      - ml-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: fraud-detection-api
    restart: on-failure
    ports:
      - "5001:5001"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "python3 -c \"import http.client; conn = http.client.HTTPConnection('localhost', 5001); conn.request('GET', '/health'); resp = conn.getresponse(); exit(0) if resp.status == 200 else exit(1)\""
        ]
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - ./:/app
    environment:
      MLFLOW_URI: ${MLFLOW_URI}
      MODEL_NAME: ${MODEL_NAME}
    depends_on:
      - mlflow
    networks:
      - ml-network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web Console
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/ready" ]
      interval: 5s
      timeout: 2s
      retries: 5
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  minio-init:
    image: minio/mc
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      mc mb -p local/cc-fraud-detection-2025 ||
      echo 'Bucket already exists'
      "

networks:
  ml-network:

volumes:
  frontend-dist:
  minio-data: