stages:
  preprocess_train:
    cmd: PYTHONPATH=. python src/dataprocessing/preprocessTrain.py
    deps:
    - data/training/fraudTrain.csv
    - src/dataprocessing/preprocessTrain.py
    outs:
    - outputs/preprocessed/train_preprocessed.csv
  train_model:
    cmd: PYTHONPATH=. python src/models/DecisionTree.py
    deps:
    - outputs/preprocessed/train_preprocessed.csv
    - src/models/DecisionTree.py
    outs:
    - outputs/models/decision_tree_model.pkl
    - outputs/models/model_run_metadata.json
    metrics:
    - outputs/metrics/decision_tree_metrics.json:
        cache: false