name: Python Lint and DVC Prep

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install flake8
        run: pip install flake8==7.2.0

      - name: Run flake8
        run: flake8 .

      - name: Install black
        run: pip install black

      - name: Check formatting with black
        run: black --check .

  tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Install DVC
        run: pip install dvc[s3]

      - name: DVC pull --remote amazon
        run: dvc pull
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1
      - name: Model Explainability
        run: python src/tests/test_model_explainability.py   